### ISSUE TITLE
Error with trying to use both third eye and with the press E

### ISSUE THREAD

**Issue by skellykat** [trainordevs/td-policedesk#4]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/47672755/154156239-8601cb13-7c60-4e2d-b217-5af332970a9a.png">

**Comment by boppescripting** [comment]
Should be fixed with the most recent commit: https://github.com/trainordevs/td-policedesk/commit/85e99df2d4a8b8ffd21a3c87a14406bcd48ec7d0.
