### ISSUE TITLE
attempt to index a nil value with new commitment 

### ISSUE THREAD

**Issue by skellykat** [trainordevs/td-policedesk#5]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/47672755/154267667-9bfb6c99-9178-485f-a3b2-200e8211ac52.png">

**Comment by boppescripting** [comment]
How up to date is your qb-core? The original function I used (QBCore.Functions.GetQBPlayers()) is the same way that qb-policejob does it. To note, when it was setup in that way, the script worked for me perfectly fine.

Please also update a screenshot of the code you have around line 6 of SV_Main.lua.

**Comment by skellykat** [comment]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/47672755/154281208-4b344e6f-c272-420a-8c6f-2458733e8419.png">
Line 6 for you
i have not updated to the most recent qb-core but i have updated to the one that uses
local QBCore = exports['qb-core']:GetCoreObject() 
instead of 
QBCore = nil 

Citizen.CreateThread(function()
	while QBCore == nil do
		TriggerEvent('QBCore:GetObject', function(obj) QBCore = obj end)
		Citizen.Wait(31)
	end
end)

**Comment by boppescripting** [comment]
Okay... once I get off work today, I will mess with the code and see what's going on.

**Comment by skellykat** [comment]
Cheers

**Comment by boppescripting** [comment]
So I reverted my commit since it seems to have been working fine. Review https://github.com/trainordevs/td-policedesk/commit/50c8b3be0073bba3e6da3810b0df5ac37341709a for the reverted changes.

Add this code to `qb-core/server/functions.lua`:
```
function QBCore.Functions.GetQBPlayers()
    return QBCore.Players
end
```

If you review https://github.com/qbcore-framework/qb-core/blob/main/server/functions.lua, the function starts on line 76.

**Comment by skellykat** [comment]
Fixed it works perfectly now with that function added in thank you :) for being so helpful and fixing these problems
