### ISSUE TITLE
<eof> expected near 'end'

### ISSUE THREAD

**Issue by TitasKe** [trainordevs/td-policedesk#6]
I got this error, when i tried to remove the **function setupTargetExport**
![image](https://user-images.githubusercontent.com/97993783/161063845-22c33b78-7c9f-4e07-8d28-5ae24346cbf6.png)

**Comment by TitasKe** [comment]
**Code:**

![image](https://user-images.githubusercontent.com/97993783/161063916-9ee87bc0-89f7-4e96-b4a7-bae0b17474d8.png)

**Comment by boppescripting** [comment]
I would have to see the entire file to see why its having the error.

For reference, that function only runs if you have the config option set for using third-eye. It's not entirely needed to remove it if you don't want to use third-eye.

**Comment by TitasKe** [comment]
I want to have a third-eye, but in ur script its bugging with qb-target in same object

Like this:
![image](https://user-images.githubusercontent.com/97993783/161082946-332e8156-660b-4687-8d1b-5569dc6747fd.png)

And sometimes it shows only button

**Comment by boppescripting** [comment]
You could just comment or remove line 26 in the client.lua so it doesn't run that function.
